# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xml_service_pb2 as xml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XMLServiceStub(object):
    """Serviço gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarXPath = channel.unary_unary(
                '/xmlservice.XMLService/ConsultarXPath',
                request_serializer=xml__service__pb2.XPathRequest.SerializeToString,
                response_deserializer=xml__service__pb2.XPathResponse.FromString,
                _registered_method=True)
        self.AgregarAtivos = channel.unary_unary(
                '/xmlservice.XMLService/AgregarAtivos',
                request_serializer=xml__service__pb2.AgregarAtivosRequest.SerializeToString,
                response_deserializer=xml__service__pb2.AgregarAtivosResponse.FromString,
                _registered_method=True)
        self.ContarAtivosPorTipo = channel.unary_unary(
                '/xmlservice.XMLService/ContarAtivosPorTipo',
                request_serializer=xml__service__pb2.ContarAtivosPorTipoRequest.SerializeToString,
                response_deserializer=xml__service__pb2.ContarAtivosPorTipoResponse.FromString,
                _registered_method=True)
        self.MediaPrecosPorTipo = channel.unary_unary(
                '/xmlservice.XMLService/MediaPrecosPorTipo',
                request_serializer=xml__service__pb2.MediaPrecosPorTipoRequest.SerializeToString,
                response_deserializer=xml__service__pb2.MediaPrecosPorTipoResponse.FromString,
                _registered_method=True)


class XMLServiceServicer(object):
    """Serviço gRPC
    """

    def ConsultarXPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarAtivos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContarAtivosPorTipo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediaPrecosPorTipo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarXPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarXPath,
                    request_deserializer=xml__service__pb2.XPathRequest.FromString,
                    response_serializer=xml__service__pb2.XPathResponse.SerializeToString,
            ),
            'AgregarAtivos': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarAtivos,
                    request_deserializer=xml__service__pb2.AgregarAtivosRequest.FromString,
                    response_serializer=xml__service__pb2.AgregarAtivosResponse.SerializeToString,
            ),
            'ContarAtivosPorTipo': grpc.unary_unary_rpc_method_handler(
                    servicer.ContarAtivosPorTipo,
                    request_deserializer=xml__service__pb2.ContarAtivosPorTipoRequest.FromString,
                    response_serializer=xml__service__pb2.ContarAtivosPorTipoResponse.SerializeToString,
            ),
            'MediaPrecosPorTipo': grpc.unary_unary_rpc_method_handler(
                    servicer.MediaPrecosPorTipo,
                    request_deserializer=xml__service__pb2.MediaPrecosPorTipoRequest.FromString,
                    response_serializer=xml__service__pb2.MediaPrecosPorTipoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xmlservice.XMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xmlservice.XMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XMLService(object):
    """Serviço gRPC
    """

    @staticmethod
    def ConsultarXPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/ConsultarXPath',
            xml__service__pb2.XPathRequest.SerializeToString,
            xml__service__pb2.XPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgregarAtivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/AgregarAtivos',
            xml__service__pb2.AgregarAtivosRequest.SerializeToString,
            xml__service__pb2.AgregarAtivosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContarAtivosPorTipo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/ContarAtivosPorTipo',
            xml__service__pb2.ContarAtivosPorTipoRequest.SerializeToString,
            xml__service__pb2.ContarAtivosPorTipoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MediaPrecosPorTipo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XMLService/MediaPrecosPorTipo',
            xml__service__pb2.MediaPrecosPorTipoRequest.SerializeToString,
            xml__service__pb2.MediaPrecosPorTipoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
